In [8]:
import numpy as np

data = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

a = np.array(data)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
a.dtype

dtype('int64')

In [10]:
type(a)

numpy.ndarray

In [12]:
dir(a)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__

In [15]:
a = a.astype(np.float32) #a = a.astype('float32')
a

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]], dtype=float32)

In [16]:
a[0][1]

2.0

In [17]:
a[0]

array([1., 2., 3.], dtype=float32)

In [18]:
np.arange(1, 10, 2)  #np.arange(start, stop, step)

array([1, 3, 5, 7, 9])

In [20]:
np.arange(1, 10).reshape(3, 3)  #reshape(a, b)에서 a*b= np.arange안에 숫자 개수랑 같아야함

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
np.arange(1, 13).reshape(3, 4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [23]:
np.arange(1, 13).reshape(3, 2, 2)  #3 =()안에 []안에 r갯수, 2 =()안에 있는 []안에 []의 갯수, 2 = 가장 작은[]안의 갯수 

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [24]:
np.nan #평균, 더하거나 빼거나 곱할 때 

nan

In [28]:
a[0][1] = np.nan

In [29]:
a

array([[ 1., nan,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.]], dtype=float32)

In [31]:
a = np.arange(1, 10).reshape(3, 3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
a[0][1] = np.nan.  #인티저에서는 nan 사용 못함

SyntaxError: invalid syntax (3900869917.py, line 1)

In [38]:
 a = np.linspace(1, 10, 10)
 a

SyntaxError: invalid syntax (230658985.py, line 2)

In [41]:
#연산

data = np.arange(1, 10).reshape(3, 3)
data

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [50]:
[1, 2, 3] + [4, 5, 6]  #파이썬에서는 리시트끼리의 연결이 됨

[1, 2, 3, 4, 5, 6]

In [47]:
data + data

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [46]:
data * data

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [44]:
data / data

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [49]:
np.dot(data, data)   #행렬의 곱

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [51]:
data@data

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [54]:
# 0차원 : 스칼라
a = np.array(1)
a
a.shape   #나오지 않는 이유는 0차원이기 때문
a.ndim    #디민션(차원)

0

In [56]:
# 1차원 : 벡터
a = np.array([1])
a
#a.shape
#a.ndim

(1,)

In [61]:
# 1차원 : 벡터
a = np.array([1, 2, 3, 4, 5])
a
a.shape    #5개의 형태를 가지고 있다
#a.ndim    #1차원이다

(5,)

In [63]:
# 2차원 : 행렬
a = np.array([[1, 2, 3], [4, 5, 6]])
a          #array 형태
a.shape    #2개의 행과 3개의 열을 가지고 있다
#a.ndim    #2차원이다

(2, 3)

In [67]:
# 2차원 : 행렬
a = np.array([[1, 2, 3]])
a          #array 형태
a.shape    #1개의 행과 3개의 열을 가지고 있다
a.ndim     #2차원이다

2

In [70]:
# 3차원 : 3차원 이상의 자차원의 행렬을 Tensor 라고 함
a = np.array([[[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]]])
a          #array 형태
#a.shape    #1개의 행과 3개의 열을 가지고 있다
#a.ndim     #2차원이다

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [73]:
### matrix의 유형

a = np.arange(12).reshape(2, 3, 2)
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [77]:
b = np.ones(12).reshape(2, 3, 2)
b

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [78]:
c = np.zeros(12).reshape(2, 3, 2)
c

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [79]:
d = np.eye(3)   #단위행렬 = 자신과 자신의 역행렬(자신을 곱했을 때 0이 나오는..)
d

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [81]:
e = np.zeros([3, 4])
e

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [82]:
e = np.zeros([3, 4, 2])
e

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [85]:
f = np.empty([2, 3])  #empty는 0에 가까운 값이 있는 값으로 채워진 것
f

array([[4.9e-324, 9.9e-324, 1.5e-323],
       [2.0e-323, 2.5e-323, 3.0e-323]])

In [87]:
g = np.full((3, 4), 100)  # (3,4)의 행렬을 100으로 채워라
g

array([[100, 100, 100, 100],
       [100, 100, 100, 100],
       [100, 100, 100, 100]])

In [89]:
h = np.linspace(2, 10, 6)
h

array([ 2. ,  3.6,  5.2,  6.8,  8.4, 10. ])

In [90]:
## 집계함수

a = np.arange(10).reshape(2, 5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [92]:
a[0][0] = 100
a

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9]])

In [94]:
a[0, 1] = 1000
a

array([[ 100, 1000,    2,    3,    4],
       [   5,    6,    7,    8,    9]])

In [96]:
np.mean(a)   #평균

114.4

In [97]:
np.median(a)   #중앙값= 작은 수에서 큰수까지 쭉 일렬로 늘어트려서 늘어트린 수. 여기에서는 짝수이므로 6과 7 가운데의 값 

6.5

In [98]:
np.std(a)  # 표준편차

296.5485457728633

In [99]:
np.var(a) # 분산

87941.04

In [100]:
np.sum(a)

1144

In [101]:
sum(a)

array([ 105, 1006,    9,   11,   13])

In [102]:
a

array([[ 100, 1000,    2,    3,    4],
       [   5,    6,    7,    8,    9]])

In [105]:
np.sum(a, axis=0)  # 열끼리 더함

array([ 105, 1006,    9,   11,   13])

In [104]:
np.sum(a, axis=1) #행끼리 더함

array([1109,   35])

In [106]:
np.max(a)

1000

In [107]:
np.min(a)

2